name: Test Echo
on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test code
        run: go test -v .
