name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          cd server
          go build -v ./...

      - name: Test
        run: |
          cd server
          go test -v ./...

  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 11.x

      - name: Install NPM packages
        run: |
          cd front
          yarn install --frozen-lockfile

      - name: Build Next.js app
        run: |
          cd front
          yarn build

      - name: Lint Next.js app
        run: |
          cd front
          yarn lint

      - name: Test Next.js app
        run: |
          cd front
          yarn test
